apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  labels:
    app: nginx-app-details
  name: ${prefix}-app-3
  namespace: ns-sub-1
spec:
  componentKinds:
   ${map}
  selector:
    matchLabels:
      app: nginx-app-details
      string: ${string}
      password: ${password}
      boolean: ${boolean}
      counter: ${counter}
      list: ${list}
      string1: ${string}
      password1: ${password}
      boolean1: ${boolean}
      counter1: ${counter}
      list1: ${list}
status: {}